[package]
name = "hmi-io-server"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
hmi-io-alarm.workspace = true
hmi-io-config.workspace = true
hmi-io-monitor.workspace = true
hmi-io-plugin.workspace = true
hmi-io-point.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["net", "sync", "rt", "macros"] }
sync-util.workspace = true
tokio-tungstenite.workspace = true
anyhow.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
