[package]
name = "hmi-io-alarm"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
hmi-io-db.workspace = true
hmi-io-point.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
log.workspace = true
sync-util.workspace = true
tokio = { workspace = true, features = ["sync", "rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "time", "rt"] }