[package]
name = "iec104-plugin"
version = "0.3.0"
edition.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen.workspace = true
serde.workspace = true
serde_json.workspace = true
iec104-core.workspace = true
plugin-kit.workspace = true
sync-util = { workspace = true, default-features = false }
